export default {
  chunk: ".chunk()",
  embeddings: ".embed()",
  "extract-params": "ExtractParams",
  rerank: "rerank()",
  document: "MDocument",
  "metadata-filters": "Metadata Filters",
  "database-config": "DatabaseConfig",
  "graph-rag": "GraphRAG",
  astra: "AstraVector",
  chroma: "ChromaVector",
  vectorize: "CloudflareVector",
  pg: "PgVector",
  libsql: "LibSQLVector",
  mongodb: "MongoDBVector",
  couchbase: "CouchbaseVector",
  opensearch: "OpenSearchVector",
  pinecone: "PineconeVector",
  qdrant: "QdrantVector",
  turbopuffer: "TurboPuffer",
  upstash: "UpstashVector",
};
