const meta = {
  workflow: "ワークフロー",
  "step-class": "ステップ",
  "step-options": "ステップオプション",
  "step-condition": "ステップ条件",
  "step-function": ".step()",
  after: ".after()",
  then: ".then()",
  until: ".until()",
  while: ".while()",
  if: ".if()",
  else: ".else()",
  createRun: ".createRun()",
  start: ".start()",
  execute: ".execute()",
  suspend: ".suspend()",
  snapshots: "スナップショット",
  resume: ".resume()",
  commit: ".commit()",
  watch: ".watch()",
  events: "イベント駆動ワークフロー",
  afterEvent: ".afterEvent()",
  resumeWithEvent: ".resumeWithEvent()",
  "step-retries": "ステップ再試行",
};

export default meta;
