name: MCP Package Tests

on:
  workflow_run:
    workflows: ['Quality assurance']
    types:
      - completed

jobs:
  check-changes:
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    outputs:
      mcp-changed: ${{ steps.changes.outputs.mcp }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set pending status
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'pending'
          context: 'MCP Package Tests'
          description: 'Checking for changes'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check for mcp package changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: main
          ref: ${{ github.event.workflow_run.head_sha }}
          filters: |
            mcp:
              - 'packages/mcp/**'

  skip-tests:
    needs: check-changes
    if: needs.check-changes.outputs.mcp-changed == 'false'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set success status for unchanged mcp
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'MCP Package Tests'
          description: 'MCP package unchanged - skipping tests'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test:
    needs: check-changes
    if: ${{ github.repository == 'mastra-ai/mastra' && needs.check-changes.outputs.mcp-changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:r
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build @mastra/mcp
        run: pnpm turbo --filter="./packages/mcp" --filter "mastra" build
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'

      - name: Run MCP tests
        run: pnpm run test:mcp
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  test-success:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.mcp-changed == 'true' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set success status for completed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'MCP Package Tests'
          description: 'All MCP tests passed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test-failure:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.mcp-changed == 'true' && needs.test.result == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set failure status for failed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'failure'
          context: 'MCP Package Tests'
          description: 'MCP tests failed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
